// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash)
VALUES ($1, $2)
RETURNING id, username
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

type CreateUserRow struct {
	ID       int64
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const getRefreshTokenValid = `-- name: GetRefreshTokenValid :one
SELECT id, user_id, expires_at
FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

type GetRefreshTokenValidRow struct {
	ID        int64
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) GetRefreshTokenValid(ctx context.Context, tokenHash string) (GetRefreshTokenValidRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenValid, tokenHash)
	var i GetRefreshTokenValidRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           int64
	Username     string
	PasswordHash string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertRefreshTokenParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked_at = now(), replaced_by = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID         int64
	ReplacedBy sql.NullInt64
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.ID, arg.ReplacedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshTokenByHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
