// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"time"
)

type Url struct {
	ID        int64
	Alias     string
	Url       string
	CreatedAt time.Time
}
