// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	ID         int64
	UserID     int64
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  sql.NullTime
	CreatedAt  time.Time
	ReplacedBy sql.NullInt64
}

type Url struct {
	ID        int64
	Alias     string
	Url       string
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}
