// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package sqlcdb

import (
	"context"
)

const saveURL = `-- name: SaveURL :one
INSERT INTO urls (alias, url)
VALUES ($1, $2)
RETURNING id, alias
`

type SaveURLParams struct {
	Alias string
	Url   string
}

type SaveURLRow struct {
	ID    int64
	Alias string
}

func (q *Queries) SaveURL(ctx context.Context, arg SaveURLParams) (SaveURLRow, error) {
	row := q.db.QueryRowContext(ctx, saveURL, arg.Alias, arg.Url)
	var i SaveURLRow
	err := row.Scan(&i.ID, &i.Alias)
	return i, err
}
